### ISSUE TITLE
How to simultaneously capture the frames from seven cameras?

### ISSUE THREAD

**Issue by marklwzbupt** [Robert-Mar/MultiviewC#2]
Thank you for your great work! I wonder how i can get results simultaneously from all seven cameras? It seems that in the single player mode i can only capture results from one camera.

**Comment by Jiahao-Ma** [comment]
You can open multiple platforms simultaneously. The first platform you open will be a server, while the others will be clients that can connect to the server. Additionally, other devices on the same network as the server can also join as clients.
